<template>
  <div class="content">
    <h1 id="importing-data">Importing</h1>
    <h2 id="limitations">Limitations</h2>
    <p>Since the Zendesk API is JSON-based, XML data imports are not supported. To learn more about formatting a file for a successful import, please view the section on <router-link to="/documentation/importing#formatting">formatting</router-link>.</p>
    <table>
      <thead>
        <tr>
          <th>Format</th>
          <th>Supported?</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>CSV</td>
          <td>Yes</td>
        </tr>
        <tr>
          <td>JSON</td>
          <td>Yes</td>
        </tr>
        <tr>
          <td>XML</td>
          <td>No</td>
        </tr>
      </tbody>
    </table>
    <h2 id="formatting">Formatting</h2>
    <p>The preferred formatting will match the exact format of exported CSV or JSON files. You can choose to omit columns unless they are required by the Zendesk API to allow creation of the resource(s).</p>
    <blockquote><strong>Note:</strong> Imports must use IDs (rather than names) for user, group, and organizations. If you are importing a file that was generated by Data Manager, you must have disabled the 'Replace IDs with names' setting.</blockquote>
  </div>
</template>

<script>
export default {
  name: 'importing-data'
}
</script>
