export default {
  articleColumns: [
    { name: 'Id', value: 'id', selected: true },
    { name: 'Title', value: 'title', selected: true },
    { name: 'Locale', value: 'locale', selected: true },
    { name: 'Brand Name', value: 'brand_name', selected: true },
    { name: 'Brand Id', value: 'brand_id', selected: true },
    { name: 'Created At', value: 'created_at', selected: true },
    { name: 'Updated At', value: 'updated_at', selected: true }
  ],
  groupColumns: [
    { name: 'Id', value: 'id', selected: true },
    { name: 'Name', value: 'name', selected: true },
    { name: 'Created At', value: 'created_at', selected: true },
    { name: 'Updated At', value: 'updated_at', selected: true }
  ],
  organizationColumns: [
    { name: 'Id', value: 'id', selected: true },
    { name: 'Name', value: 'name', selected: true },
    { name: 'Details', value: 'details', selected: true },
    { name: 'Tags', value: 'tags', selected: true },
    { name: 'Created At', value: 'created_at', selected: true },
    { name: 'Updated At', value: 'updated_at', selected: true },
    { name: 'External Id', value: 'external_id', selected: false },
    { name: 'Group Id', value: 'group_id', selected: false },
    { name: 'Notes', value: 'notes', selected: false },
  ],
  ticketColumns: [
    { name: 'Id', value: 'id', selected: true },
    { name: 'Subject', value: 'subject', selected: true },
    { name: 'Type', value: 'type', selected: true },
    { name: 'Group Id', value: 'group_id', selected: true },
    { name: 'Assignee Id', value: 'assignee_id', selected: true, sideload: {type: 'users'} },
    { name: 'Requester Id', value: 'requester_id', selected: true, sideload: {type: 'users'} },
    { name: 'Status', value: 'status', selected: true },
    { name: 'Priority', value: 'priority', selected: true },
    { name: 'Created At', value: 'created_at', selected: true },
    { name: 'Updated At', value: 'updated_at', selected: true },
    { name: 'External Id', value: 'external_id', selected: false },
    { name: 'Channel', value: 'channel', selected: false },
    { name: 'Description', value: 'description', selected: false },
    { name: 'Recipient', value: 'recipient', selected: false },
    { name: 'Submitter Id', value: 'submitter_id', selected: false, sideload: {type: 'users'} },
    { name: 'Organization Id', value: 'organization_id', selected: false, sideload: {type: 'organizations'} },
    { name: 'Collaborator Ids', value: 'collaborator_ids', selected: false, sideload: {type: 'users'} },
    { name: 'Forum Topic Id', value: 'forum_topic_id', selected: false },
    { name: 'Problem Id', value: 'problem_id', selected: false },
    { name: 'Due At', value: 'due_at', selected: false },
    { name: 'Brand Id', value: 'brand_id', selected: false },
    { name: 'Has Incidents', value: 'has_incidents', selected: false },
    { name: 'Tags', value: 'tags', selected: false },
    { name: 'Satisfaction Rating', value: 'satisfaction_rating', selected: false }
  ],
  userColumns: [
    { name: 'Id', value: 'id', selected: true },
    { name: 'Name', value: 'name', selected: true },
    { name: 'Email', value: 'email', selected: true },
    { name: 'Phone', value: 'phone', selected: true },
    { name: 'Organization Id', value: 'organization_id', selected: true, sideload: {type: 'organizations'} },
    { name: 'Role', value: 'role', selected: true },
    { name: 'Tags', value: 'tags', selected: true },
    { name: 'Created At', value: 'created_at', selected: true },
    { name: 'Updated At', value: 'updated_at', selected: true },
    { name: 'External Id', value: 'external_id', selected: false },
    { name: 'Active', value: 'active', selected: false },
    { name: 'Chat Only', value: 'chat_only', selected: false },
    { name: 'Last Login At', value: 'last_login_at', selected: false },
    { name: 'Notes', value: 'notes', selected: false },
    { name: 'Time Zone', value: 'time_zone', selected: false },
    { name: 'Locale', value: 'locale', selected: false },
    { name: 'Verified', value: 'verified', selected: false }
  ]
}
